(case when  k6002<>桥幅名称 then '桥幅名称不一致' else '' end ) IS NOT NULL AND
(case when  k6003<>中心桩号 then '中心桩号不一致' else '' end ) IS NOT NULL AND
(case when  k6008<>桥梁全长 then '桥梁全长不一致' else '' end ) IS NOT NULL AND
(case when  K6065<>跨径总长 then '跨径总长不一致' else '' end ) IS NOT NULL AND
(case when  k6063<>最大跨径 then '最大跨径不一致' else '' end ) IS NOT NULL AND
(case when  k6066<>桥面总宽 then '桥面总宽不一致' else '' end ) IS NOT NULL AND
(case when  k6009<>桥面净宽 then '桥面净宽不一致' else '' end ) IS NOT NULL AND
(case when  hk6007<>跨径分类 then '跨径分类不一致' else '' end ) IS NOT NULL AND
(case when  hk6004<>桥梁性质 then '桥梁性质不一致' else '' end ) IS NOT NULL AND
(case when  hk6016<>主桥上部类型 then '主桥上部类型不一致' else '' end ) IS NOT NULL AND
(case when  HK6110<>主桥上部材料 then '主桥上部材料不一致' else '' end ) IS NOT NULL AND
(case when  hk6017<>桥墩类型 then '桥墩类型不一致' else '' end ) IS NOT NULL AND
(case when  hk6022<>设计荷载等级 then '设计荷载等级不一致' else '' end ) IS NOT NULL AND
(case when  hk6023<>抗震等级 then '抗震等级不一致' else '' end ) IS NOT NULL AND
(case when hk6005<>跨越地物类型 then '跨越地物类型不一致' else '' end ) IS NOT NULL AND
(case when k6006<>跨越地物名称 then '跨越地物名称不一致' else '' end ) IS NOT NULL AND
(case when hK6024<>通航等级 then '通航等级不一致' else '' end ) IS NOT NULL AND
(case when ha1328<>墩台防撞设施类型 then '墩台防撞设施类型不一致' else '' end ) IS NOT NULL AND
(case when k6062<>是否互通立交 then '是否互通立交不一致' else '' end ) IS NOT NULL AND
(case when k6079<>建设单位 then '建设单位不一致' else '' end ) IS NOT NULL AND
(case when k6030<>设计单位 then '设计单位不一致' else '' end ) IS NOT NULL AND
(case when K6031<>施工单位 then '施工单位不一致' else '' end ) IS NOT NULL AND
(case when K6032<>监理单位 then '监理单位不一致' else '' end ) IS NOT NULL AND
(case when K0180<>修建年度 then '修建年度不一致' else '' end ) IS NOT NULL AND
(case when K0116<>通车时间 then '通车时间不一致' else '' end ) IS NOT NULL AND
(case when hA1313<>管养单位性质 then '管养单位性质不一致' else '' end ) IS NOT NULL AND
(case when a1314<>[管理（养）单位] then '管理单位不一致' else '' end ) IS NOT NULL AND
(case when K6111<>监管单位 then '监管单位不一致' else '' end ) IS NOT NULL AND
(case when ha1302<>收费性质 then '收费性质不一致' else '' end ) IS NOT NULL AND
(case when hk6028<>桥梁技术状况 then '桥梁技术状况不一致' else '' end ) IS NOT NULL AND
(case when a1305<>最近评定日期 then '最近评定日期不一致' else '' end ) IS NOT NULL AND
(case when ha1307<>交通管制措施 then '交通管制措施不一致' else '' end ) IS NOT NULL AND
(case when ha0103<>所在政区 then '所在政区不一致' else '' end ) IS NOT NULL AND
(case when hk6117<>行车方向 then '行车方向不一致' else '' end ) IS NOT NULL AND
(case when hk6118<>是否宽路窄桥 then '是否宽路窄桥不一致' else '' end ) IS NOT NULL AND
(case when hk6119<>是否在长大桥梁目录 then '是否在长大桥梁目录不一致' else '' end ) IS NOT NULL AND
(case when hk6120<>是否为跨省桥梁 then '是否为跨省桥梁不一致' else '' end) IS NOT NULL 
